### PR TITLE
GH-754: Gas Price Optimisation - Hot Fix

### LINKED ISSUE #754: Gas Price Optimisation - Hot Fix
The Gas Price is increased by 30% during retries, which can easily become a very high value after few retires. Increase this value gracefully to prevent the user to overspend their money.

### PR DESCRIPTION
**Pull request by utkarshg6**
> [!NOTE]
> Replaces margin-based gas logic with percentage-based increases and a constant bump for retries, updating constants, computation, and tests across pricing and blockchain layers.
> 
> - **Gas pricing logic**:
>   - Replace `DEFAULT_GAS_PRICE_MARGIN` with `DEFAULT_GAS_PRICE_RETRY_PERCENTAGE` and add `DEFAULT_GAS_PRICE_RETRY_CONSTANT` in `masq_lib/src/constants.rs`.
>   - Rename `increase_gas_price_by_margin` to `increase_by_percentage` in `node/src/blockchain/blockchain_bridge.rs` and update all callers (`priced/new.rs`, `agent_web3.rs`, `blockchain_interface_web3/mod.rs`, `blockchain_interface_initializer.rs`).
>   - Retry computation change in `priced/retry.rs`:
>     - If `latest_gas_price_wei >= prev_gas_price_wei` -> use `increase_by_percentage(latest)`.
>     - Else -> use `prev + DEFAULT_GAS_PRICE_RETRY_CONSTANT`.
>   - Enforce gas price ceiling using the new calculations and adjust related log messages.
> - **Tests**:
>   - Update expected values to use `increase_by_percentage` and new retry rules across `agent_web3.rs`, `blockchain_bridge.rs`, `blockchain_interface_web3/mod.rs`, and initializer tests.
>   - Add unit tests for `compute_gas_price` behavior in `priced/retry.rs`.
>   - Adjust fee estimations and expected logs to reflect new pricing formula.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 82cc8b7d73f933a83dc54abc6c2deba801224b55. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: node/src/accountant/scanners/payable_scanner/tx_templates/priced/retry.rs [hunk 1]
```diff
@@ -167,3 +170,44 @@ impl RetryLogBuilder {
         }
     }
 }
+
+#[cfg(test)]
+mod tests {
+    use super::*;
+
+    #[test]
+    fn compute_gas_price_increases_by_percentage_if_latest_if_higher() {
```
Comment (bertllll) [inline node/src/accountant/scanners/payable_scanner/tx_templates/priced/retry.rs]: ...if_latest_is_higher()

File: node/src/accountant/scanners/payable_scanner/tx_templates/priced/retry.rs [hunk 2]
```diff
@@ -167,3 +170,44 @@ impl RetryLogBuilder {
...
+        let latest_gas_price_wei = 120;
+        let prev_gas_price_wei = 100;
```
Comment (bertllll) [inline node/src/accountant/scanners/payable_scanner/tx_templates/priced/retry.rs:181]: Could you please use a value bigger just by one than the other? 101 and 100

File: node/src/accountant/scanners/payable_scanner/tx_templates/priced/retry.rs [hunk 3]
```diff
@@ -167,3 +170,44 @@ impl RetryLogBuilder {
...
+
+        let computed_gas_price =
+            PricedRetryTxTemplate::compute_gas_price(latest_gas_price_wei, prev_gas_price_wei);
+
+        let expected_gas_price = prev_gas_price_wei + DEFAULT_GAS_PRICE_RETRY_CONSTANT;
+        assert_eq!(computed_gas_price, expected_gas_price);
+    }
+
+    #[test]
+    fn compute_gas_price_increases_by_percentage_if_latest_if_equal() {
```
Comment (bertllll) [inline node/src/accountant/scanners/payable_scanner/tx_templates/priced/retry.rs]: ...if_latest_is_equal()

And could you please switch the positions of this test an the one above? I think it would work for a more logical ordering.

File: node/src/accountant/scanners/payable_scanner/tx_templates/priced/retry.rs [hunk 4]
```diff
@@ -167,3 +170,44 @@ impl RetryLogBuilder {
...
+            PricedRetryTxTemplate::compute_gas_price(latest_gas_price_wei, prev_gas_price_wei);
+
+        let expected_gas_price = increase_by_percentage(latest_gas_price_wei);
+        assert_eq!(computed_gas_price, expected_gas_price);
+    }
+
+    #[test]
+    fn compute_gas_price_increments_previous_by_constant_if_latest_is_lower() {
+        let latest_gas_price_wei = 80;
+        let prev_gas_price_wei = 100;
```
Comment (bertllll) [inline node/src/accountant/scanners/payable_scanner/tx_templates/priced/retry.rs:193]: Also here, can you pls have these two values different by just one?

File: node/src/blockchain/blockchain_interface/blockchain_interface_web3/mod.rs [hunk 5]
```diff
@@ -906,32 +907,32 @@ mod tests {
...
             RetryTxTemplates(vec![retry_1.clone(), retry_2.clone(), retry_3.clone()]);
         let expected_retry_tx_templates = PricedRetryTxTemplates(vec![
-            PricedRetryTxTemplate::new(retry_1, increase_gas_price_by_margin(gas_price_from_rpc)),
-            PricedRetryTxTemplate::new(retry_2, increase_gas_price_by_margin(gas_price_from_rpc)),
+            PricedRetryTxTemplate::new(retry_1, increase_by_percentage(latest_gas_price_wei)),
+            PricedRetryTxTemplate::new(retry_2, increase_by_percentage(latest_gas_price_wei)),
             PricedRetryTxTemplate::new(
                 retry_3,
-                increase_gas_price_by_margin(gas_price_from_rpc + 1),
+                latest_gas_price_wei + 1 + DEFAULT_GAS_PRICE_RETRY_CONSTANT,
```
Comment (bertllll) [inline node/src/blockchain/blockchain_interface/blockchain_interface_web3/mod.rs]: Optional: you can even notate this as `(latest_gas_price_wei + 1) + DEFAULT_GAS_PRICE_RETRY_CONSTANT`

File: node/src/blockchain/blockchain_agent/agent_web3.rs [hunk 6]
```diff
@@ -170,30 +172,32 @@ mod tests {
...
-                RetryTxTemplate {
-                    base: BaseTxTemplate::from(&account),
-                    prev_gas_price_wei,
-                    prev_nonce: idx as u64,
-                }
-            })
-            .collect_vec()
+            prev_gas_prices
+                .clone()
+                .into_iter()
```
Comment (bertllll) [inline node/src/blockchain/blockchain_agent/agent_web3.rs]: Maybe possible as 

.iter()
.copied()

File: node/src/blockchain/blockchain_agent/agent_web3.rs [hunk 7]
```diff
@@ -205,23 +209,28 @@ mod tests {
...
+            let computed_gas_prices = prev_gas_prices
+                .into_iter()
+                .map(|prev_gas_price_wei| {
+                    PricedRetryTxTemplate::compute_gas_price(
+                        latest_gas_price_wei,
+                        prev_gas_price_wei,
+                    )
+                })
+                .collect::<Vec<u128>>();
+            if computed_gas_prices.len() != retry_tx_templates.len() {
```
Comment (bertllll) [inline node/src/blockchain/blockchain_agent/agent_web3.rs:221]: There is an empty line lower here which would look better erased.

File: node/src/blockchain/blockchain_agent/agent_web3.rs [hunk 8]
```diff
@@ -382,18 +392,17 @@ mod tests {
...
         let account_2 = make_payable_account(34);
         let ceiling_gas_price_wei = chain.rec().gas_price_safe_ceiling_minor;
-        // This should be the value that would surplus the ceiling just slightly if the margin is applied
-        let border_gas_price_wei =
-            (ceiling_gas_price_wei * 100) / (DEFAULT_GAS_PRICE_MARGIN as u128 + 100) + 2;
-        let rpc_gas_price_wei = border_gas_price_wei - 1;
-        let check_value_wei = increase_gas_price_by_margin(border_gas_price_wei);
+        // Once the gas price is computed from latest and prev gas price values, it'll break the ceiling
+        let prev_gas_price_wei = ceiling_gas_price_wei + 1 - DEFAULT_GAS_PRICE_RETRY_CONSTANT;
+        let latest_gas_price_wei = prev_gas_price_wei - 100; // Any value lower than prev will work
```
Comment (bertllll) [inline node/src/blockchain/blockchain_agent/agent_web3.rs]: I might prefer just a minus 1. (With deleting the comment...)

File: node/src/blockchain/blockchain_agent/agent_web3.rs [hunk 9]
```diff
@@ -602,39 +611,40 @@ mod tests {
...
-                RetryTxTemplate {
-                    base: BaseTxTemplate::from(&account),
-                    prev_gas_price_wei,
-                    prev_nonce: idx as u64,
-                }
-            })
-            .collect()
+            prev_gas_prices
+                .clone()
+                .into_iter()
```
Comment (bertllll) [inline node/src/blockchain/blockchain_agent/agent_web3.rs]: Perhaps same here. But you know what? I'm not crazy about it.

**Review by bertllll — APPROVED** [review]
